@currency_inator_HostAddress = http://localhost:5231

GET {{currency_inator_HostAddress}}/ping/
Accept: application/json

###

GET {{currency_inator_HostAddress}}/USD/2024-12-12
Accept: application/json
